<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OrbitMesh.OpenWeather</RootNamespace>
    <AssemblyName>OrbitMesh.OpenWeather</AssemblyName>
    <Version>1.1.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OrbitMesh.Common" Version="1.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="PackageInfo.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="openweather_icon.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="settings.json" Condition="Exists('settings.json')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
